import Head from "next/head";
import Navbar from "./component/Navbar";
import PageProvider from "./PageProvider";
import "./globals.css";
import { inter } from "./utils/fonts";
import { MenuProvider } from "./context/menu_context";
import Sidebar from "./component/Sidebar";

export const metadata = {
  title: "Roy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" style={{scrollBehavior:'smooth'}}>
      <Head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0,user-scalable=0"
        />
      </Head>
      <body className={inter.className}>
        <PageProvider>
          <MenuProvider>
            <Navbar>
              <Sidebar />
              {children}
            </Navbar>
          </MenuProvider>
        </PageProvider>
      </body>
    </html>
  );
}
