import Head from "next/head";
import Navbar from "./component/Navbar";
import PageProvider from "./PageProvider";
import "./globals.css";
import { MenuProvider } from "./context/menu_context";
import Sidebar from "./component/Sidebar";
import { ModalProvider } from "./context/modal_context";

import Inter from "next/font";
export const metadata = {
  title: "Roy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0,user-scalable=0"
        />
      </Head>
      <body>
        <PageProvider>
          <ModalProvider>
            <MenuProvider>
              <Navbar>
                <Sidebar />

                {children}
              </Navbar>
            </MenuProvider>
          </ModalProvider>
        </PageProvider>
      </body>
    </html>
  );
}
